let balance=107;const cart=[];let deliveryInterval=null,curseShownThisSession=false;const $=id=>document.getElementById(id);
const balanceEl=$("balance"),cartCountEl=$("cartCount"),cartItemsEl=$("cartItems"),cartTotalEl=$("cartTotal"),messageEl=$("message"),gameMessageEl=$("gameMessage");
const cartOverlay=$("cartOverlay"),openCartBtn=$("openCartBtn"),closeCartBtn=$("closeCartBtn"),checkoutBtn=$("checkoutBtn"),clearCartBtn=$("clearCartBtn"),earnBtn=$("earnBtn");
const openRulesBtn=$("openRulesBtn"),closeRulesBtn=$("closeRulesBtn"),rulesOverlay=$("rulesOverlay"),fireworksEl=$("fireworks");
const deliveryBox=$("deliveryBox"),deliveryFill=$("deliveryFill"),deliveryCat=$("deliveryCat"),deliveryStatus=$("deliveryStatus"),deliveryActions=$("deliveryActions"),receivedBtn=$("receivedBtn"),missingBtn=$("missingBtn");
const curseOverlay=$("curseOverlay"),curseSpendBtn=$("curseSpendBtn"),curseEarnBtn=$("curseEarnBtn"),keep67Btn=$("keep67Btn"),screamerOverlay=$("screamerOverlay");
const detailsOverlay=$("detailsOverlay"),closeDetailsBtn=$("closeDetailsBtn"),detailsTitle=$("detailsTitle"),detailsVideo=$("detailsVideo"),detailsText=$("detailsText"),detailsStats=$("detailsStats");
const balanceMenuBtn=$("balanceMenuBtn"),balanceOverlay=$("balanceOverlay"),closeBalanceMenuBtn=$("closeBalanceMenuBtn"),showPromoBtn=$("showPromoBtn"),promoBox=$("promoBox"),promoInput=$("promoInput"),applyPromoBtn=$("applyPromoBtn"),promoMessage=$("promoMessage"),earnFromMenuBtn=$("earnFromMenuBtn");
const usedPromos=new Set();

const catDetails={mini:{title:"МаМини",video:"images/mama_mini.MP4",text:"Маленький кот с огромным самомнением. Делает вид, что ничего не понимает, но уже посчитал твой баланс.",stats:["Редкость: маленькая легенда","Любимая еда: крошка рыбки","Риск побега: 12%"]},pineapple:{title:"Ананасовый Ма",video:"images/mama_pineapple.mp4",text:"Кот в ананасовой броне. Выглядит как фрукт, но внутри бизнес-план и лёгкое осуждение.",stats:["Редкость: тропический","Любимая еда: лосось с зонтиком","Риск побега: 34%"]},cute:{title:"МаМилашка",video:"images/mama_cute.mp4",text:"Слишком милый кот. Опасность в том, что после просмотра хочется отдать ему все КотоКоины.",stats:["Редкость: милая угроза","Любимая еда: комплименты","Риск побега: 5%"]},hat2:{title:"МаШляпа 2",video:"images/mama_another_hat.mp4",text:"Кот, который знает про стиль больше, чем весь подъезд. Смотрит прямо в душу и требует уважения.",stats:["Редкость: модный босс","Любимая еда: внимание","Риск побега: 67%"]},hat:{title:"МаШляпа",video:"images/mama_hat.mp4",text:"Главная модница МаМагазина. Может ничего не делать, но всё равно выглядит как владелец бренда.",stats:["Редкость: легендарная","Любимая еда: розовый корм","Риск побега: 22%"]}};
const deliveryPhrases=["Выбежал из сайта 🐈","Ищет подъезд по запаху котлет 🥩","Пересекает дорогу и делает вид, что он главный 🚦","Едет на поезде без билета 🚆","Проверяет адрес лапкой 🐾","Застрял в розовом пакете 🎀","Спорит с курьером-мяу 📦","Покупает себе рыбку по дороге 🐟","Пытается открыть домофон носом 👃","Сел на лавочку подумать о жизни 🪑","Убеждает голубя уступить дорогу 🕊️","Проверяет, точно ли ты оплатил КотоКоинами 💰","Переходит через лужу как аристократ 💅","Случайно зашёл не в тот подъезд 🏢","Пишет маме, что почти приехал 📱","Остановился погладить самого себя 😼","Идёт по карте, но карта нарисована лапой 🗺️","Слишком красиво идёт, прохожие снимают сторис 📸","Пытается ехать на самокате 🛴","Упал, встал, сделал вид, что так и надо 😾","Спросил дорогу у другого кота 🐈‍⬛","Несёт заказ, но подозрительно мурчит 📦","Забыл зачем шёл, но продолжил движение 🧠","Обходит собаку по дипломатическим причинам 🐕","Почти у дома, но решил пройтись красиво ✨","Зашёл в магазин за влажным кормом 🛒","Ускорился: почувствовал запах квартиры 🏠","Видит дверь и делает важное лицо 🚪","Стоит у коврика и ждёт оваций 🐾","У двери 🚪"];

function updateBalance(){balanceEl.textContent=balance}
function getCartTotal(){return cart.reduce((s,i)=>s+i.price,0)}
function animateElement(e){if(!e)return;e.classList.remove("pop");void e.offsetWidth;e.classList.add("pop")}
function animateButton(b){if(!b)return;b.classList.remove("button-pop");void b.offsetWidth;b.classList.add("button-pop")}
function renderCart(){cartCountEl.textContent=cart.length;cartTotalEl.textContent=getCartTotal();if(!cart.length){cartItemsEl.textContent="Пока пусто. Коты обижены.";return}cartItemsEl.innerHTML=cart.map((i,n)=>`<div class="cart-row"><div class="cart-row-info"><div>${i.name}</div><div class="cart-row-price">${i.price} КотоКоинов</div></div><button class="remove-item" data-index="${n}">×</button></div>`).join("");document.querySelectorAll(".remove-item").forEach(b=>b.addEventListener("click",()=>removeFromCart(Number(b.dataset.index))))}
function maybeShowCurseAfterPurchase(){if(!curseShownThisSession&&balance===67){curseShownThisSession=true;curseOverlay.classList.add("active")}}
function addToCart(name,price,button){if(balance<price){messageEl.textContent=`Не хватает ${price-balance} КотоКоинов. Иди тыкать лапу 🐾`;openCart();animateElement(document.querySelector(".balance"));return}balance-=price;cart.push({name,price});updateBalance();renderCart();animateElement(document.querySelector(".balance"));animateButton(button);messageEl.textContent=`${name} добавлен в корзину. Списано ${price} КотоКоинов 🐾`;maybeShowCurseAfterPurchase()}
function removeFromCart(index){const item=cart[index];if(!item)return;balance+=item.price;cart.splice(index,1);updateBalance();renderCart();animateElement(document.querySelector(".balance"));messageEl.textContent=`${item.name} убран из корзины. Вернули ${item.price} КотоКоинов 😼`}
function clearCart(){const refund=getCartTotal();if(!cart.length){messageEl.textContent="Корзина и так пустая, бро.";return}balance+=refund;cart.length=0;updateBalance();renderCart();resetDelivery();animateElement(document.querySelector(".balance"));messageEl.textContent=`Корзина очищена. Вернули ${refund} КотоКоинов.`}
function openCart(){cartOverlay.classList.add("active");renderCart()}
function closeCart(){cartOverlay.classList.remove("active")}
function resetDelivery(){if(deliveryInterval){clearInterval(deliveryInterval);deliveryInterval=null}deliveryBox.classList.remove("active");deliveryActions.classList.remove("active");deliveryFill.style.width="0%";deliveryCat.style.left="0%";deliveryStatus.textContent="Кот пока сидит в корзине."}
function getRandomDeliveryRoute(){const final="У двери 🚪",arr=deliveryPhrases.filter(p=>p!==final).sort(()=>Math.random()-.5).slice(0,6);return[...arr,final]}
function startDelivery(){const route=getRandomDeliveryRoute();let step=0;deliveryBox.classList.add("active");deliveryActions.classList.remove("active");deliveryFill.style.width="0%";deliveryCat.style.left="0%";deliveryStatus.textContent="Кот готовится к доставке 🐾";if(deliveryInterval)clearInterval(deliveryInterval);function move(){const progress=Math.round(step/(route.length-1)*100);deliveryFill.style.width=`${progress}%`;deliveryCat.style.left=`${progress}%`;deliveryStatus.textContent=route[step];if(step>=route.length-1){clearInterval(deliveryInterval);deliveryInterval=null;deliveryFill.style.width="100%";deliveryCat.style.left="100%";deliveryStatus.textContent="У двери 🚪";setTimeout(()=>deliveryActions.classList.add("active"),800);return}step++}move();deliveryInterval=setInterval(move,3000)}
function checkout(){if(!cart.length){messageEl.textContent="Сначала выбери кота, бро 😭";return}cart.length=0;renderCart();messageEl.textContent="Мяу-заказ оформлен! Запускаем доставку кота 🐈";startDelivery()}
function orderReceived(){messageEl.textContent="Спасибо за заказ! Кот официально принят в семью 😺";deliveryStatus.textContent="Заказ получен. Кот доволен 🐾";deliveryActions.classList.remove("active");launchFireworks()}
function orderMissing(){messageEl.textContent="Кота нет, потому что это шуточная игра 😭 Настоящие коты через сайт не доставляются. Но МаМагазин всё равно ценит твоё терпение.";deliveryStatus.textContent="Курьер-мяу растворился в мемах 😿";deliveryActions.classList.remove("active")}
function openRules(){rulesOverlay.classList.add("active")}function closeRules(){rulesOverlay.classList.remove("active")}
function openDetails(key){const c=catDetails[key];if(!c)return;detailsTitle.textContent=c.title;detailsVideo.src=c.video;detailsText.textContent=c.text;detailsStats.innerHTML=c.stats.map(s=>`<div>${s}</div>`).join("");detailsOverlay.classList.add("active")}
function closeDetails(){detailsOverlay.classList.remove("active");detailsVideo.pause();detailsVideo.src=""}
function launchFireworks(){fireworksEl.innerHTML="";fireworksEl.classList.add("active");for(let i=0;i<60;i++){const p=document.createElement("div");p.className="firework";const x=Math.random()*innerWidth,y=Math.random()*innerHeight*.6,mx=(Math.random()-.5)*260,my=(Math.random()-.5)*260;p.style.left=`${x}px`;p.style.top=`${y}px`;p.style.setProperty("--x",`${mx}px`);p.style.setProperty("--y",`${my}px`);fireworksEl.appendChild(p)}setTimeout(()=>{fireworksEl.classList.remove("active");fireworksEl.innerHTML=""},1000)}
function earnCoins(){const base=Math.floor(Math.random()*5)+1;let mult=1,text="Обычный тык 🐾";const chance=Math.random();if(chance<.05){mult=5;text="ДЖЕКПОТ-МЯУ! x5 😼🔥";launchFireworks()}else if(chance<.25){mult=2;text="Крит-мяу! x2 😺"}const reward=base*mult;balance+=reward;updateBalance();$("lastDrop").textContent=reward;$("multiplier").textContent=`x${mult}`;gameMessageEl.textContent=`+${reward} КотоКоинов. ${text}`;animateElement(document.querySelector(".balance"));animateElement(earnBtn)}
function curseSpend(){curseOverlay.classList.remove("active");openCart();messageEl.textContent="Потрать хотя бы один КотоКоин, пока сайт не передумал 😰"}
function curseEarn(){curseOverlay.classList.remove("active");document.querySelector(".game").scrollIntoView({behavior:"smooth",block:"center"})}
function keep67(){curseOverlay.classList.remove("active");screamerOverlay.classList.add("active");setTimeout(()=>screamerOverlay.classList.remove("active"),1800)}
function openBalanceMenu(){balanceOverlay.classList.add("active")}function closeBalanceMenu(){balanceOverlay.classList.remove("active")}
function applyPromo(){const code=promoInput.value.trim().toUpperCase();const promos={MEOW:20,AERISGOLD:50,MAMA:30};if(!code){promoMessage.textContent="Сначала введи промокод 😼";return}if(usedPromos.has(code)){promoMessage.textContent="Этот промокод уже использован 🐾";return}if(!promos[code]){promoMessage.textContent="Такого промокода коты не знают 😿";return}usedPromos.add(code);balance+=promos[code];updateBalance();promoMessage.textContent=`Промокод принят! +${promos[code]} КотоКоинов 🎁`;animateElement(document.querySelector(".balance"))}

document.querySelectorAll(".buy-btn").forEach(b=>b.addEventListener("click",()=>addToCart(b.dataset.name,Number(b.dataset.price),b)));
document.querySelectorAll(".details-btn").forEach(b=>b.addEventListener("click",()=>openDetails(b.dataset.cat)));
openCartBtn.addEventListener("click",openCart);closeCartBtn.addEventListener("click",closeCart);checkoutBtn.addEventListener("click",checkout);clearCartBtn.addEventListener("click",clearCart);earnBtn.addEventListener("click",earnCoins);
openRulesBtn.addEventListener("click",openRules);closeRulesBtn.addEventListener("click",closeRules);receivedBtn.addEventListener("click",orderReceived);missingBtn.addEventListener("click",orderMissing);
curseSpendBtn.addEventListener("click",curseSpend);curseEarnBtn.addEventListener("click",curseEarn);keep67Btn.addEventListener("click",keep67);
closeDetailsBtn.addEventListener("click",closeDetails);balanceMenuBtn.addEventListener("click",openBalanceMenu);closeBalanceMenuBtn.addEventListener("click",closeBalanceMenu);
showPromoBtn.addEventListener("click",()=>promoBox.classList.toggle("active"));applyPromoBtn.addEventListener("click",applyPromo);earnFromMenuBtn.addEventListener("click",()=>{closeBalanceMenu();document.querySelector(".game").scrollIntoView({behavior:"smooth",block:"center"})});
cartOverlay.addEventListener("click",e=>{if(e.target===cartOverlay)closeCart()});rulesOverlay.addEventListener("click",e=>{if(e.target===rulesOverlay)closeRules()});detailsOverlay.addEventListener("click",e=>{if(e.target===detailsOverlay)closeDetails()});balanceOverlay.addEventListener("click",e=>{if(e.target===balanceOverlay)closeBalanceMenu()});
updateBalance();renderCart();resetDelivery();
